services:
  - type: web
    name: fake-news-detector
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m nltk.downloader stopwords
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.8
